export { PointOfSale } from '@styled-icons/material/PointOfSale'
export { ListOl } from '@styled-icons/boxicons-regular/ListOl'
export { Motorcycle } from '@styled-icons/fa-solid/Motorcycle'
export { ArrowLeftRight } from '@styled-icons/bootstrap/ArrowLeftRight'
export { BarChart } from '@styled-icons/ionicons-sharp/BarChart'
export { Cashapp } from '@styled-icons/simple-icons/Cashapp'
export { HomeAlt } from '@styled-icons/boxicons-regular/HomeAlt'
export { CashRegister } from '@styled-icons/fa-solid/CashRegister'
export { RemoveCircle, AddCircle } from '@styled-icons/material'
export { Offer, AddToQueue, User } from '@styled-icons/boxicons-solid'
export { ArrowFromLeft, ArrowFromRight } from '@styled-icons/boxicons-regular'
export { CloseOutline } from '@styled-icons/evaicons-outline'
export { Repeat } from '@styled-icons/evaicons-solid/Repeat'
export { Receipt } from '@styled-icons/ionicons-solid/Receipt'
export { StatusOffline } from '@styled-icons/heroicons-solid/StatusOffline'
